### ISSUE TITLE
Attacking skills to check for correctness

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-DL/dragalia-data-parse-2#1]
- [ ] Gala Bahamut RaenonX-DL/dragalia-data-parse#57
- [ ] Undercover Grace RaenonX-DL/dragalia-data-parse#44
- [ ] Valentine's Chelsea and Ryszarda RaenonX-DL/dragalia-data-parse#30
- [ ] P5S units RaenonX-DL/dragalia-data-parse#25
- [ ] Faris
- [ ] Eirene, Finni
- [ ] G!Notte
- [ ] Myriam
- [ ] Alberius
- [ ] HuMerc
